/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * CadastroBenificiario
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-23T20:01:43.978Z")
public class CadastroBenificiario {
  @SerializedName("idCartao")
  private BigDecimal idCartao = null;

  @SerializedName("idCartaoDestino")
  private BigDecimal idCartaoDestino = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("cpf")
  private BigDecimal cpf = null;

  public CadastroBenificiario idCartao(BigDecimal idCartao) {
    this.idCartao = idCartao;
    return this;
  }

   /**
   * Número identificador referente ao proxy do cartão origem de transferência.
   * @return idCartao
  **/
  @ApiModelProperty(example = "null", value = "Número identificador referente ao proxy do cartão origem de transferência.")
  public BigDecimal getIdCartao() {
    return idCartao;
  }

  public void setIdCartao(BigDecimal idCartao) {
    this.idCartao = idCartao;
  }

  public CadastroBenificiario idCartaoDestino(BigDecimal idCartaoDestino) {
    this.idCartaoDestino = idCartaoDestino;
    return this;
  }

   /**
   * Número identificador referente ao proxy do cartão destino de transferência.
   * @return idCartaoDestino
  **/
  @ApiModelProperty(example = "null", value = "Número identificador referente ao proxy do cartão destino de transferência.")
  public BigDecimal getIdCartaoDestino() {
    return idCartaoDestino;
  }

  public void setIdCartaoDestino(BigDecimal idCartaoDestino) {
    this.idCartaoDestino = idCartaoDestino;
  }

  public CadastroBenificiario nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome completo do beneficiário da transferência.
   * @return nome
  **/
  @ApiModelProperty(example = "null", value = "Nome completo do beneficiário da transferência.")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public CadastroBenificiario cpf(BigDecimal cpf) {
    this.cpf = cpf;
    return this;
  }

   /**
   * Numero do cadastro de pessoas física do beneficiário da transferência.
   * @return cpf
  **/
  @ApiModelProperty(example = "null", value = "Numero do cadastro de pessoas física do beneficiário da transferência.")
  public BigDecimal getCpf() {
    return cpf;
  }

  public void setCpf(BigDecimal cpf) {
    this.cpf = cpf;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CadastroBenificiario cadastroBenificiario = (CadastroBenificiario) o;
    return Objects.equals(this.idCartao, cadastroBenificiario.idCartao) &&
        Objects.equals(this.idCartaoDestino, cadastroBenificiario.idCartaoDestino) &&
        Objects.equals(this.nome, cadastroBenificiario.nome) &&
        Objects.equals(this.cpf, cadastroBenificiario.cpf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCartao, idCartaoDestino, nome, cpf);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CadastroBenificiario {\n");
    
    sb.append("    idCartao: ").append(toIndentedString(idCartao)).append("\n");
    sb.append("    idCartaoDestino: ").append(toIndentedString(idCartaoDestino)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    cpf: ").append(toIndentedString(cpf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

