/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * CartaoDisponivel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-23T20:01:43.978Z")
public class CartaoDisponivel {
  @SerializedName("idCartao")
  private BigDecimal idCartao = null;

  public CartaoDisponivel idCartao(BigDecimal idCartao) {
    this.idCartao = idCartao;
    return this;
  }

   /**
   * Número identificador referente ao proxy do cartão.
   * @return idCartao
  **/
  @ApiModelProperty(example = "null", value = "Número identificador referente ao proxy do cartão.")
  public BigDecimal getIdCartao() {
    return idCartao;
  }

  public void setIdCartao(BigDecimal idCartao) {
    this.idCartao = idCartao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartaoDisponivel cartaoDisponivel = (CartaoDisponivel) o;
    return Objects.equals(this.idCartao, cartaoDisponivel.idCartao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCartao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartaoDisponivel {\n");
    
    sb.append("    idCartao: ").append(toIndentedString(idCartao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

