/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.NovoCartao;

/**
 * SetNovoCartao
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-23T20:01:43.978Z")
public class SetNovoCartao {
  @SerializedName("cartao")
  private NovoCartao cartao = null;

  public SetNovoCartao cartao(NovoCartao cartao) {
    this.cartao = cartao;
    return this;
  }

   /**
   * Get cartao
   * @return cartao
  **/
  @ApiModelProperty(example = "null", value = "")
  public NovoCartao getCartao() {
    return cartao;
  }

  public void setCartao(NovoCartao cartao) {
    this.cartao = cartao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetNovoCartao setNovoCartao = (SetNovoCartao) o;
    return Objects.equals(this.cartao, setNovoCartao.cartao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cartao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetNovoCartao {\n");
    
    sb.append("    cartao: ").append(toIndentedString(cartao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

