/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SetPagamento
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-23T20:01:43.978Z")
public class SetPagamento {
  @SerializedName("idCartao")
  private String idCartao = null;

  @SerializedName("senha")
  private String senha = null;

  @SerializedName("codigoBarras")
  private String codigoBarras = null;

  public SetPagamento idCartao(String idCartao) {
    this.idCartao = idCartao;
    return this;
  }

   /**
   * Número identificador referente ao proxy do cartão.
   * @return idCartao
  **/
  @ApiModelProperty(example = "null", value = "Número identificador referente ao proxy do cartão.")
  public String getIdCartao() {
    return idCartao;
  }

  public void setIdCartao(String idCartao) {
    this.idCartao = idCartao;
  }

  public SetPagamento senha(String senha) {
    this.senha = senha;
    return this;
  }

   /**
   * Senha do cartão.
   * @return senha
  **/
  @ApiModelProperty(example = "null", value = "Senha do cartão.")
  public String getSenha() {
    return senha;
  }

  public void setSenha(String senha) {
    this.senha = senha;
  }

  public SetPagamento codigoBarras(String codigoBarras) {
    this.codigoBarras = codigoBarras;
    return this;
  }

   /**
   * Código de pagamento identificado no documento (boleto).
   * @return codigoBarras
  **/
  @ApiModelProperty(example = "null", value = "Código de pagamento identificado no documento (boleto).")
  public String getCodigoBarras() {
    return codigoBarras;
  }

  public void setCodigoBarras(String codigoBarras) {
    this.codigoBarras = codigoBarras;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetPagamento setPagamento = (SetPagamento) o;
    return Objects.equals(this.idCartao, setPagamento.idCartao) &&
        Objects.equals(this.senha, setPagamento.senha) &&
        Objects.equals(this.codigoBarras, setPagamento.codigoBarras);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCartao, senha, codigoBarras);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetPagamento {\n");
    
    sb.append("    idCartao: ").append(toIndentedString(idCartao)).append("\n");
    sb.append("    senha: ").append(toIndentedString(senha)).append("\n");
    sb.append("    codigoBarras: ").append(toIndentedString(codigoBarras)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

