/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * SetTransferencia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-23T20:01:43.978Z")
public class SetTransferencia {
  @SerializedName("idCartao")
  private BigDecimal idCartao = null;

  @SerializedName("idCartaoDestino")
  private BigDecimal idCartaoDestino = null;

  @SerializedName("valor")
  private Double valor = null;

  @SerializedName("senha")
  private String senha = null;

  public SetTransferencia idCartao(BigDecimal idCartao) {
    this.idCartao = idCartao;
    return this;
  }

   /**
   * Número identificador referente ao proxy do cartão origem de transferência.
   * @return idCartao
  **/
  @ApiModelProperty(example = "null", value = "Número identificador referente ao proxy do cartão origem de transferência.")
  public BigDecimal getIdCartao() {
    return idCartao;
  }

  public void setIdCartao(BigDecimal idCartao) {
    this.idCartao = idCartao;
  }

  public SetTransferencia idCartaoDestino(BigDecimal idCartaoDestino) {
    this.idCartaoDestino = idCartaoDestino;
    return this;
  }

   /**
   * Número identificador referente ao proxy do cartão destino de transferência.
   * @return idCartaoDestino
  **/
  @ApiModelProperty(example = "null", value = "Número identificador referente ao proxy do cartão destino de transferência.")
  public BigDecimal getIdCartaoDestino() {
    return idCartaoDestino;
  }

  public void setIdCartaoDestino(BigDecimal idCartaoDestino) {
    this.idCartaoDestino = idCartaoDestino;
  }

  public SetTransferencia valor(Double valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor monetário a ser transferido.
   * @return valor
  **/
  @ApiModelProperty(example = "null", value = "Valor monetário a ser transferido.")
  public Double getValor() {
    return valor;
  }

  public void setValor(Double valor) {
    this.valor = valor;
  }

  public SetTransferencia senha(String senha) {
    this.senha = senha;
    return this;
  }

   /**
   * Senha do cartão.
   * @return senha
  **/
  @ApiModelProperty(example = "null", value = "Senha do cartão.")
  public String getSenha() {
    return senha;
  }

  public void setSenha(String senha) {
    this.senha = senha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetTransferencia setTransferencia = (SetTransferencia) o;
    return Objects.equals(this.idCartao, setTransferencia.idCartao) &&
        Objects.equals(this.idCartaoDestino, setTransferencia.idCartaoDestino) &&
        Objects.equals(this.valor, setTransferencia.valor) &&
        Objects.equals(this.senha, setTransferencia.senha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCartao, idCartaoDestino, valor, senha);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetTransferencia {\n");
    
    sb.append("    idCartao: ").append(toIndentedString(idCartao)).append("\n");
    sb.append("    idCartaoDestino: ").append(toIndentedString(idCartaoDestino)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    senha: ").append(toIndentedString(senha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

