/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SetTransferencia;

/**
 * Transferencia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-23T20:01:43.978Z")
public class Transferencia {
  @SerializedName("transferencia")
  private SetTransferencia transferencia = null;

  public Transferencia transferencia(SetTransferencia transferencia) {
    this.transferencia = transferencia;
    return this;
  }

   /**
   * Get transferencia
   * @return transferencia
  **/
  @ApiModelProperty(example = "null", value = "")
  public SetTransferencia getTransferencia() {
    return transferencia;
  }

  public void setTransferencia(SetTransferencia transferencia) {
    this.transferencia = transferencia;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transferencia transferencia = (Transferencia) o;
    return Objects.equals(this.transferencia, transferencia.transferencia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferencia);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transferencia {\n");
    
    sb.append("    transferencia: ").append(toIndentedString(transferencia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

