/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.MsgErro;
import io.swagger.client.model.Pagamento;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PagamentosApi
 */
@Ignore
public class PagamentosApiTest {

    private final PagamentosApi api = new PagamentosApi();

    
    /**
     * Pagamento de boletos.
     *
     * &lt;p&gt;Permite o pagamento de boletos.&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pagamentosPostTest() throws ApiException {
        Pagamento boleto = null;
        api.pagamentosPost(boleto);

        // TODO: test validations
    }
    
}
