/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.MsgErro;
import io.swagger.client.model.Transferencia;
import io.swagger.client.model.TransferenciaCadastroBenificiario;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransferenciasApi
 */
@Ignore
public class TransferenciasApiTest {

    private final TransferenciasApi api = new TransferenciasApi();

    
    /**
     * Cadastro de beneficiário
     *
     * &lt;p&gt;Permite o cadastro de beneficiário para uma transferencia.&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transferenciasCadastrosPostTest() throws ApiException {
        TransferenciaCadastroBenificiario beneficiario = null;
        api.transferenciasCadastrosPost(beneficiario);

        // TODO: test validations
    }
    
    /**
     * Transferência de valor
     *
     * &lt;p&gt;Permite a transferência de valor entre dois cartões pré cadastrados.&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transferenciasPostTest() throws ApiException {
        Transferencia transferencia = null;
        api.transferenciasPost(transferencia);

        // TODO: test validations
    }
    
}
