/*
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.MsgErro;
import io.swagger.client.model.Transferencia;
import io.swagger.client.model.TransferenciaCadastroBenificiario;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TransferenciasApi {
    private ApiClient apiClient;

    public TransferenciasApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TransferenciasApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for transferenciasCadastrosPost */
    private com.squareup.okhttp.Call transferenciasCadastrosPostCall(TransferenciaCadastroBenificiario beneficiario, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = beneficiario;
        
        // create path and map variables
        String localVarPath = "/transferencias/cadastros".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "access_token", "key_id", "client_id" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call transferenciasCadastrosPostValidateBeforeCall(TransferenciaCadastroBenificiario beneficiario, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'beneficiario' is set
        if (beneficiario == null) {
            throw new ApiException("Missing the required parameter 'beneficiario' when calling transferenciasCadastrosPost(Async)");
        }
        
        
        com.squareup.okhttp.Call call = transferenciasCadastrosPostCall(beneficiario, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Cadastro de beneficiário
     * &lt;p&gt;Permite o cadastro de beneficiário para uma transferencia.&lt;/p&gt;
     * @param beneficiario Objeto de requisição (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void transferenciasCadastrosPost(TransferenciaCadastroBenificiario beneficiario) throws ApiException {
        transferenciasCadastrosPostWithHttpInfo(beneficiario);
    }

    /**
     * Cadastro de beneficiário
     * &lt;p&gt;Permite o cadastro de beneficiário para uma transferencia.&lt;/p&gt;
     * @param beneficiario Objeto de requisição (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> transferenciasCadastrosPostWithHttpInfo(TransferenciaCadastroBenificiario beneficiario) throws ApiException {
        com.squareup.okhttp.Call call = transferenciasCadastrosPostValidateBeforeCall(beneficiario, null, null);
        return apiClient.execute(call);
    }

    /**
     * Cadastro de beneficiário (asynchronously)
     * &lt;p&gt;Permite o cadastro de beneficiário para uma transferencia.&lt;/p&gt;
     * @param beneficiario Objeto de requisição (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call transferenciasCadastrosPostAsync(TransferenciaCadastroBenificiario beneficiario, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = transferenciasCadastrosPostValidateBeforeCall(beneficiario, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for transferenciasPost */
    private com.squareup.okhttp.Call transferenciasPostCall(Transferencia transferencia, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = transferencia;
        
        // create path and map variables
        String localVarPath = "/transferencias".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "access_token", "key_id", "client_id" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call transferenciasPostValidateBeforeCall(Transferencia transferencia, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'transferencia' is set
        if (transferencia == null) {
            throw new ApiException("Missing the required parameter 'transferencia' when calling transferenciasPost(Async)");
        }
        
        
        com.squareup.okhttp.Call call = transferenciasPostCall(transferencia, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Transferência de valor
     * &lt;p&gt;Permite a transferência de valor entre dois cartões pré cadastrados.&lt;/p&gt;
     * @param transferencia Objeto de requisição (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void transferenciasPost(Transferencia transferencia) throws ApiException {
        transferenciasPostWithHttpInfo(transferencia);
    }

    /**
     * Transferência de valor
     * &lt;p&gt;Permite a transferência de valor entre dois cartões pré cadastrados.&lt;/p&gt;
     * @param transferencia Objeto de requisição (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> transferenciasPostWithHttpInfo(Transferencia transferencia) throws ApiException {
        com.squareup.okhttp.Call call = transferenciasPostValidateBeforeCall(transferencia, null, null);
        return apiClient.execute(call);
    }

    /**
     * Transferência de valor (asynchronously)
     * &lt;p&gt;Permite a transferência de valor entre dois cartões pré cadastrados.&lt;/p&gt;
     * @param transferencia Objeto de requisição (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call transferenciasPostAsync(Transferencia transferencia, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = transferenciasPostValidateBeforeCall(transferencia, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
